package main;

import main.entities.HeapNode;
import main.entities.HuffmanEncodingTree;
import main.helpers.HuffmanTreeHelper;

import java.io.*;
import java.util.Objects;
import java.util.Scanner;

/**
 * Lab03 Main class that executes Huffmann Encoding and returns encoded value
 *
 * @author Jung Woo J Jeong
 * @version 1.0 2022-04-17
 */
class Lab03 {

  /**
   * Main method executing all 4 tasks
   * 1. Print out the tree in preorder traversal
   * 2. Printout the resulting encoding generated by the tree
   * 3. Outputs encoded strings from ClearText.txt
   * 4. Outputs decoded strings from Encoded.txt
   * @param args
   * @throws IOException
   */
  public static void main(String[] args) throws IOException {

    String freqTableFilePath = args[0];
    String clearTextFilePath = args[1];
    String encodedTextFilePath = args[2];
    String encodeOutputFilePath = args[3];
    String decodeOutputFilePath = args[4];


    HuffmanTreeHelper htHelper = new HuffmanTreeHelper(freqTableFilePath,
            clearTextFilePath, encodedTextFilePath);

    HeapNode heTree = htHelper.generateHuffmanTree();

    htHelper.generateHuffmanTreePreorderTraversal(heTree);
    HuffmanTreeHelper.displayLetterEncodeValuesFromFrequencyTable(heTree,
            freqTableFilePath);
    HuffmanTreeHelper.displayEncodedValues(heTree, clearTextFilePath,
            encodeOutputFilePath);
    HuffmanTreeHelper.displayDecodedValues(heTree, encodedTextFilePath,
            decodeOutputFilePath);










  }

}